### PR TITLE
Starting to add PHPDoc to classes

### PR DESCRIPTION
**Pull request by napolux**
Thanks for contributing to Postleaf! 💙💚

### Pull Request Summary

The code format sucks. ;)
I've started to create [PHPDoc](https://www.phpdoc.org/) comments for classes, if this 1st PR is ok for you I can go on with the rest of the code

### Have you...

- [X] Checked that your code adheres to our code guidelines?

---

### Contributor License Agreement

We want Postleaf to remain free and open for everyone to use forever, so please don’t submit any code or content that is licensed or copyrighted without first getting written consent.

Before we accept your pull request, we ask that you agree to the following terms to ensure there are no conflicts with Postleaf’s license now or in the future.

1. I certify that the code I am contributing to this project is completely original or free of any known license or copyright.

2. I agree to allow the developer of Postleaf, A Beautiful Site, LLC, license or relicense my work at their discretion. By submitting this pull request, I agree to forfeit all copyrights, intellectual property rights, and royalties pertaining to my contribution.

3. By entering my name in the space provided below, I agree to all of the terms mentioned above.

Signed: **Francesco Napoletano**

Date: **2016-08-03**

### CODE REVIEW

**Comment by claviska** [comment]
This is another thing I like to avoid during development since it creates overhead. It's almost time though...

That said, I'm really not a fan of most auto-doc generators. I agree that class methods need to have better documentation, but why PHPDoc? What are the alternatives? I'd prefer to look at all our options before selecting one.

My preference is one whose convention uses minimal commenting and, if it's going into a document viewer, I don't want it looking broken [like this](https://demo.phpdoc.org/Clean/classes/FeatureContext.html).

I appreciate the effort, and if PHPDoc is indeed the right choice we'll go that route. But I would like to at least take a look at our options before committing to a particular format.

Maybe @calmdev can provide some advice here, as he's done some great work with PHP doc systems in the past.

**Comment by napolux** [comment]
AFAIK PHPDoc is the "de facto" standard for PHP projects. 
All major IDE for PHP (PHPStorm and others) supports PHPDoc. 

BTW [Doxygen](http://www.stack.nl/~dimitri/doxygen/) could be a viable alternative.

I'll wait for a final decision on this.

**Comment by calmdev** [comment]
Great idea! I've worked with both and would choose phpdoc over doxygen. AFAIK doxygen doesn't provide an official package for composer. However, PHPdoc does and the packagist ecosystem appears to be more prevalent. IMO, it would be a good idea to provide the tools for generating the documentation with Postleaf 🍃  as dev dependencies within `composer.json` if the community wants to go this route.  

Maybe even expand on gulp's tasks to generate them as part of the build process. Packaging the documentation tool here will also help ensure the docs are being generated consistently by using the local copy that ships with Postleaf :shipit: 

Beyond that I think it would be nice to see at least one fully documented class and an example of the proposed output before placing forth the effort to document all classes. It's easy to double the  source lines of code going all out on this. So I'd try to find a good balance between what's useful vs too much info at this stage. 

Def would be sad to see an output like what @claviska linked above. TBH, I'd even consider forking a PHPdoc theme and customizing it a bit to make it your own under the Postleaf org @claviska maybe the community has suggestions for a phpdoc theme that can be used as a starting point. The project deserves nice documentation to match it.

**Comment by claviska** [comment]
Moved to #81 so we can focus on this after beta.

**Pull request closed without merging**
